export const words =[ "shoe", "pace", "shine", "knuckle", "home","mystery", "mercury",
"love", "tender", "rock", "bed", "haven", "spring", "temple", "sharp",
"timid", "leasure", "pie", "happiness", "sharp", "wild", "list", "young", "expectation",
"solve", "loose", "faith", "trouble", "ease", "play", "price", "wear", "word",
 "random", "sorrow", "eat", "mirror", "short", "charge", "pillow", "point", "door",
"peace", "push", "pair", "river", "hang", "bride", "vision", "run", "honey", "read", "look",
"silver", "ship", "neck", "narrow", "never", "crack", "fall", "open", "soul", "monkey",
 "anyone", "lucky", "point", "under", "smoke", "people", "sugar", "sun", "sand", "messy",
"fish", "wash", "ship", "polish", "absurd", "air", "appear", "apple", "barren", "bright", "boom",
"brick", "bored", "bliss", "booty", "border", "boss", "bizarre", "bounce", "blank",
"blend", "bread", "bye", "breach", "brave", "brawl", "brat", "cage", "chew", "comfortable", "child",
"calm", "chip", "chord", "composed", "captive", "careless", "laugh", "light", "luck", "creative", "confident",
"clay", "confused", "climb", "connect","ly", "s", "ed","her", "me", "I", "himself", "herself", "and","s", "was",
"is", "has", "it", "them", "then", "this", "in", "while", "when", "were", "where", "blanket", "learn",
"under", "over", "around", "before", "begin", "on", "after", "up", "down", "by"];
